"use client";
import { useState, useEffect } from "react";
import { mathApi, type SubjectInfo } from "@/lib/api";
import { useAuthStore } from "@/store/auth";
import { MathOutput } from "@/components/MathOutput";
import { BookOpen, Loader2, ChevronDown, Search, ChevronRight } from "lucide-react";

const LEVELS = [
  { value: "middle_school", label: "Middle School" },
  { value: "high_school",   label: "High School" },
  { value: "ap_ib",         label: "AP / IB" },
  { value: "university",    label: "University" },
  { value: "graduate",      label: "Graduate" },
];

const MODELS = [
  { value: "gpt-4o",          label: "GPT-4o" },
  { value: "gpt-4o-mini",     label: "GPT-4o Mini" },
  { value: "claude-sonnet-4", label: "Claude Sonnet 4" },
];

export default function ExplorePage() {
  const { user } = useAuthStore();
  const [subjects, setSubjects] = useState<SubjectInfo[]>([]);
  const [selected, setSelected] = useState<SubjectInfo | null>(null);
  const [topic, setTopic]       = useState("");
  const [level, setLevel]       = useState(user?.level || "high_school");
  const [model, setModel]       = useState("gpt-4o");
  const [examples, setExamples] = useState(3);
  const [running, setRunning]   = useState(false);
  const [output, setOutput]     = useState<string | null>(null);
  const [error, setError]       = useState<string | null>(null);

  useEffect(() => {
    mathApi.subjects()
      .then(({ data }) => { setSubjects(data.subjects); setSelected(data.subjects[1]); })
      .catch(() => {});
  }, []);

  const handleExplore = async () => {
    if (!topic.trim()) return;
    setRunning(true); setOutput(null); setError(null);
    try {
      const { data } = await mathApi.explore({
        topic: topic.trim(),
        subject: selected?.key || "algebra",
        level,
        example_count: examples,
        model_name: model,
        max_tokens: 4096,
      });
      setOutput(data.output_text || "");
    } catch (err: any) {
      setError(err?.response?.data?.detail || "Exploration failed.");
    } finally {
      setRunning(false);
    }
  };

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-1">
          <BookOpen className="w-5 h-5 text-violet-600" />
          <h1 className="text-xl font-bold text-gray-900">Topic Explorer</h1>
        </div>
        <p className="text-sm text-gray-500">Deep-dive any mathematical concept. Theory, examples, and practice — all generated by AI.</p>
      </div>

      <div className="grid lg:grid-cols-[280px_1fr] gap-6">
        {/* Subject selector */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-4 h-fit">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Subject</p>
          <div className="space-y-1">
            {subjects.map((s) => (
              <button key={s.key}
                onClick={() => { setSelected(s); setTopic(""); setOutput(null); }}
                className={`w-full flex items-center justify-between px-3 py-2.5 rounded-xl text-sm font-medium transition-all ${
                  selected?.key === s.key
                    ? "bg-brand-600 text-white"
                    : "text-gray-700 hover:bg-gray-50"
                }`}>
                {s.label}
                {selected?.key === s.key && <ChevronRight className="w-3.5 h-3.5" />}
              </button>
            ))}
          </div>
        </div>

        {/* Right panel */}
        <div className="space-y-5">
          {/* Topic input */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
              {selected?.label} — Choose a topic
            </p>

            {/* Topic chips */}
            {selected?.topics && (
              <div className="flex flex-wrap gap-2 mb-4">
                {selected.topics.map((t) => (
                  <button key={t} onClick={() => setTopic(t)}
                    className={`text-xs px-3 py-1.5 rounded-full border font-medium transition-all ${
                      topic === t
                        ? "bg-brand-600 text-white border-brand-600"
                        : "border-gray-200 text-gray-600 hover:border-brand-300 hover:text-brand-700 bg-white"
                    }`}>
                    {t}
                  </button>
                ))}
              </div>
            )}

            {/* Custom topic */}
            <div className="relative mb-4">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <input type="text" value={topic} onChange={(e) => setTopic(e.target.value)}
                placeholder={`Or type a specific ${selected?.label || "math"} topic…`}
                className="w-full border border-gray-200 rounded-xl pl-10 pr-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-400 bg-gray-50 focus:bg-white" />
            </div>

            {/* Settings */}
            <div className="grid grid-cols-3 gap-3 mb-4">
              {[
                { label: "Level", value: level, set: setLevel, opts: LEVELS },
                { label: "AI Model", value: model, set: setModel, opts: MODELS },
                { label: "Examples", value: String(examples), set: (v: string) => setExamples(Number(v)),
                  opts: [2,3,4,5].map((n) => ({ value: String(n), label: `${n} examples` })) },
              ].map(({ label, value, set, opts }) => (
                <div key={label}>
                  <label className="block text-xs font-medium text-gray-500 mb-1">{label}</label>
                  <div className="relative">
                    <select value={value} onChange={(e) => set(e.target.value)}
                      className="w-full border border-gray-200 rounded-lg px-3 py-2 text-xs bg-gray-50 focus:outline-none focus:ring-2 focus:ring-brand-400 appearance-none pr-7">
                      {opts.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
                    </select>
                    <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-gray-400 pointer-events-none" />
                  </div>
                </div>
              ))}
            </div>

            <button onClick={handleExplore} disabled={running || !topic.trim()}
              className="w-full py-3 rounded-xl font-bold text-white text-sm transition-all disabled:opacity-50 flex items-center justify-center gap-2 hover:shadow-lg"
              style={{ background: "linear-gradient(135deg, #7c3aed, #4338ca)" }}>
              {running ? <><Loader2 className="w-4 h-4 animate-spin" />Exploring…</> : <><BookOpen className="w-4 h-4" />Explore {topic || "topic"}</>}
            </button>
          </div>

          {/* Error */}
          {error && <div className="bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-sm text-red-700">{error}</div>}

          {/* Output */}
          {output && (
            <div className="bg-white rounded-2xl border border-gray-200 shadow-sm px-7 py-6 animate-slide-up overflow-x-auto">
              <MathOutput content={output} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
